### ISSUE TITLE
[Enhancement]: Add a dropdown for the Lists

### ISSUE THREAD

**Issue by VSCPlays** [RyanLua/Signs#30]
### Contact Details

https://devforum.roblox.com/u/vscplays/summary

### Is your feature request related to a problem?

I have an problem when getting the fonts, colors, aspect ratios and more

### Describe the solution you'd like

I would like to see a dropdown of the choice sections 

### Describe alternatives you've considered

I have considered that you have a dropdown for each section, however, there isn’t a dropdown for choice ones, maybe like a subsection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanLua** [comment]
I've already planned a solution for this problem by having it open another window for selecting over 100+ fonts and more in the Signs GitHub Project.

https://github.com/users/RyanLua/projects/1/views/3?pane=issue&itemId=28499928

Development of this will be slowed for now due to the significantly smaller anticipated install volume and how Signs isn't that high priority anymore.
